#!/usr/bin/env php
<?php
require_once('vendor/autoload.php');

use Symfony\Component\Console\Application;

#Phinx commands
use Phinx\Console\Command as Migration;
use Core\Commands as KSMVC;

$application = new Application("KSMVC", '0.1.0');

$main_commands = [
	new Migration\Migrate(),
	new Migration\Rollback(),
];

$make_commands = [
	(new Migration\Create())->setName('make:migration'),
	new KSMVC\ControllerMakeCommand(),
	new KSMVC\ModelMakeCommand(),
];

//Import Phinx's commands into our own Application
$phinx_commands = [
    new Migration\Init(),
	new Migration\Create(),
	new Migration\Migrate(),
	new Migration\Rollback(),
	new Migration\Status(),
	new Migration\Test(),
	new Migration\SeedCreate(),
	new Migration\SeedRun(),
];

foreach ($phinx_commands as $command) {
    $command->setName('migration:' . $command->getName());
}

$application->addCommands($make_commands);
$application->addCommands($phinx_commands);
$application->addCommands($main_commands);
//Run it
$application->run();
